mongo_db:
  url: mongodb://admin:adminpassword@localhost/user_game_events_db?authSource=admin
  connection: 
    pool:
      min: 1
      max: 100
    # optional params
    # connect_timeout:
    # idle_timeout: 

server:
  port: 3005

postgres_url:
  url: postgres://demo:secret@localhost:5432/vortex?application_name=cerotis

redis_url:
  url: redis://localhost:6379

kafka:
  broker:
    urls: localhost:9092
  consumer:
    - id: user
      topic:
        - user
      client_id: user.client.id
      group_id: user.group.id
    - id: game
      topic:
        - game
      client_id: game.client.id
      group_id: game.group.id
  producer:
    client_id:  cerotis
    transactional_id: cerotis-transactions
  schema_registry:
    url: http://localhost:8081
  topic:
    mappings:
      - id: user
        topic_name: user
        partitions: 2
      - id: game
        topic_name: game
        partitions: 2

mqtt:
  dflt_broker: "tcp://127.0.0.1:1883"
  dflt_client: "event_subscriptions_"
  dflt_topic_user:
    - "user_events/+"
  dflt_qos_user:
    - 0
  dflt_topic_game:
    - "game_events/+"
  dflt_qos_game:
    - 1
